module xpm_tpdram_wrapper #(
    parameter int DEPTH = 256,
    parameter int DATA_WIDTH = 32,
    parameter int ADDR_WIDTH_A = (DEPTH > 1) ? $clog2(DEPTH) : 1,
    parameter int ADDR_WIDTH_B = (DEPTH > 1) ? $clog2(DEPTH) : 1,
    parameter int READ_LATENCY_A = 1,
    parameter int READ_LATENCY_B = 1,
    parameter MEMORY_PRIMITIVE = "block",
    parameter WRITE_MODE_A = "read_first",
    parameter WRITE_MODE_B = "read_first",
    parameter MEMORY_INIT_FILE = "none",
    parameter bit USE_MEM_INIT = 1'b0,
    parameter bit USE_MEM_INIT_MMI = 1'b0,
    parameter int MEMORY_SIZE = DEPTH * DATA_WIDTH
) (
    input  wire                      clk,
    input  wire                      ena_i,
    input  wire [ADDR_WIDTH_A-1:0]   addra_i,
    input  wire [DATA_WIDTH-1:0]     dina_i,
    input  wire [(DATA_WIDTH/8)-1:0] wea_i,
    output wire [DATA_WIDTH-1:0]     douta_o,
    input  wire                      enb_i,
    input  wire [ADDR_WIDTH_B-1:0]   addrb_i,
    input  wire [DATA_WIDTH-1:0]     dinb_i,
    input  wire [(DATA_WIDTH/8)-1:0] web_i,
    output wire [DATA_WIDTH-1:0]     doutb_o
);
    wire dbiterra_unused;
    wire dbiterrb_unused;
    wire sbiterra_unused;
    wire sbiterrb_unused;

    xpm_memory_tdpram #(
        .ADDR_WIDTH_A(ADDR_WIDTH_A),
        .ADDR_WIDTH_B(ADDR_WIDTH_B),
        .AUTO_SLEEP_TIME(0),
        .BYTE_WRITE_WIDTH_A(8),
        .BYTE_WRITE_WIDTH_B(8),
        .CASCADE_HEIGHT(0),
        .CLOCKING_MODE("common_clock"),
        .ECC_BIT_RANGE("7:0"),
        .ECC_MODE("no_ecc"),
        .ECC_TYPE("none"),
        .IGNORE_INIT_SYNTH(0),
        .MEMORY_INIT_FILE(MEMORY_INIT_FILE),
        .MEMORY_INIT_PARAM("0"),
        .MEMORY_OPTIMIZATION("true"),
        .MEMORY_PRIMITIVE(MEMORY_PRIMITIVE),
        .MEMORY_SIZE(MEMORY_SIZE),
        .MESSAGE_CONTROL(0),
        .RAM_DECOMP("auto"),
        .READ_DATA_WIDTH_A(DATA_WIDTH),
        .READ_DATA_WIDTH_B(DATA_WIDTH),
        .READ_LATENCY_A(READ_LATENCY_A),
        .READ_LATENCY_B(READ_LATENCY_B),
        .READ_RESET_VALUE_A("0"),
        .READ_RESET_VALUE_B("0"),
        .RST_MODE_A("SYNC"),
        .RST_MODE_B("SYNC"),
        .SIM_ASSERT_CHK(0),
        .USE_EMBEDDED_CONSTRAINT(0),
        .USE_MEM_INIT(USE_MEM_INIT),
        .USE_MEM_INIT_MMI(USE_MEM_INIT_MMI),
        .WAKEUP_TIME("disable_sleep"),
        .WRITE_DATA_WIDTH_A(DATA_WIDTH),
        .WRITE_DATA_WIDTH_B(DATA_WIDTH),
        .WRITE_MODE_A(WRITE_MODE_A),
        .WRITE_MODE_B(WRITE_MODE_B),
        .WRITE_PROTECT(1)
    ) u_xpm_memory_tdpram (
        .dbiterra(dbiterra_unused),
        .dbiterrb(dbiterrb_unused),
        .douta(douta_o),
        .doutb(doutb_o),
        .sbiterra(sbiterra_unused),
        .sbiterrb(sbiterrb_unused),
        .addra(addra_i),
        .addrb(addrb_i),
        .clka(clk),
        .clkb(clk),
        .dina(dina_i),
        .dinb(dinb_i),
        .ena(ena_i),
        .enb(enb_i),
        .injectdbiterra(1'b0),
        .injectdbiterrb(1'b0),
        .injectsbiterra(1'b0),
        .injectsbiterrb(1'b0),
        .regcea(1'b1),
        .regceb(1'b1),
        .rsta(1'b0),
        .rstb(1'b0),
        .sleep(1'b0),
        .wea(wea_i),
        .web(web_i)
    );
endmodule
