from building import *

cwd = GetCurrentDir()
src = []

if GetDepend('BSP_USING_MTIME_TICK'):
    src += ['drv_mtime.c']

group = DefineGroup('Ydrasil Drivers', src, depend=[''], CPPPATH=[cwd, '../board'])

Return('group')
