#!/usr/bin/env python3
"""Generate an ordered Vivado source-sync Tcl fragment from Bender."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path


MODULE_RE = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)\b", re.MULTILINE)
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT_RE = re.compile(r"//.*?$", re.MULTILINE)

DEFAULT_DEFINES = ["SYNTHESIS", "TARGET_FPGA", "TARGET_SYNTHESIS", "TARGET_VIVADO", "TARGET_XILINX"]
WRAPPER_ORDER = [
    "xpm_spram_wrapper.sv",
    "xpm_tpdram_wrapper.sv",
    "xpm_sdpram_wrapper.sv",
    "xpm_init_bram_wrapper.sv",
]


def unique(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def tcl_quote(value: str) -> str:
    return "{" + value.replace("}", "\\}") + "}"


def strip_comments(text: str) -> str:
    return LINE_COMMENT_RE.sub("", BLOCK_COMMENT_RE.sub("", text))


def modules_in_file(path: Path) -> set[str]:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return set()
    return set(MODULE_RE.findall(strip_comments(text)))


def walk_manifest(node: object, files: list[str], incdirs: list[str], defines: list[str]) -> None:
    if not isinstance(node, dict):
        return

    for incdir in node.get("include_dirs", []) or []:
        incdirs.append(str(Path(incdir).resolve()))

    node_defines = node.get("defines", {}) or {}
    if isinstance(node_defines, dict):
        defines.extend(str(key) for key in node_defines.keys())

    for item in node.get("files", []) or []:
        if isinstance(item, str):
            files.append(str(Path(item).resolve()))
        else:
            walk_manifest(item, files, incdirs, defines)


def run_bender_sources(bender: str, bender_dir: Path, targets: list[str]) -> dict:
    cmd = [bender, "--no-progress", "-d", str(bender_dir), "sources"]
    for target in targets:
        cmd.extend(["-t", target])

    try:
        proc = subprocess.run(
            cmd,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        raise SystemExit(f"error: bender executable not found: {bender}") from None
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.stderr)
        raise SystemExit(f"error: bender sources failed with exit code {exc.returncode}") from None

    return json.loads(proc.stdout)


def wrapper_files(wrapper_dir: Path) -> list[Path]:
    ordered = [wrapper_dir / name for name in WRAPPER_ORDER if (wrapper_dir / name).is_file()]
    ordered_names = {path.name for path in ordered}
    rest = sorted(
        path for path in wrapper_dir.glob("*.sv")
        if path.name not in ordered_names
    )
    return ordered + rest


def staged_relative_path(path: Path, repo_root: Path) -> Path:
    """Map repository RTL into a compact, relocatable Vivado source tree."""
    try:
        relative = path.resolve().relative_to(repo_root)
    except ValueError:
        raise SystemExit(f"error: source is outside repository: {path}") from None

    parts = relative.parts
    if len(parts) >= 4 and parts[:2] == ("hw", "ip") and parts[3] == "rtl":
        return Path(parts[2], *parts[4:])
    if len(parts) >= 4 and parts[:3] == ("hw", "ip", "vendor"):
        return Path("vendor", *parts[3:])
    if len(parts) >= 3 and parts[:2] == ("hw", "ip"):
        return Path(*parts[2:])
    return relative


def copy_file(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and source.read_bytes() != destination.read_bytes():
        raise SystemExit(
            f"error: staged source collision: {source} and {destination}")
    shutil.copy2(source, destination)


def stage_include_dir(source_dir: Path, destination_dir: Path) -> None:
    for source in source_dir.rglob("*"):
        if source.is_file():
            copy_file(source, destination_dir / source.relative_to(source_dir))


def write_tcl(
    out: Path,
    source_files: list[str],
    include_dirs: list[str],
    defines: list[str],
    memory_files: list[str],
    metadata: dict[str, object],
) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write("# Generated by syn/prep_vivado_sources.py. Do not edit by hand.\n")
        f.write(f"# Metadata: {json.dumps(metadata, sort_keys=True)}\n\n")

        f.write(
            "set syn_project_dir [file normalize "
            "[get_property DIRECTORY [current_project]]]\n"
        )
        f.write(
            "set syn_source_root [file join $syn_project_dir "
            "Ydrasil_FPGA.srcs sources_1]\n\n"
        )

        f.write("set syn_source_files [list \\\n")
        for path in source_files:
            f.write(f"    [file join $syn_source_root {tcl_quote(path)}] \\\n")
        f.write("]\n\n")

        f.write("set syn_include_dirs [list \\\n")
        for path in include_dirs:
            f.write(f"    [file join $syn_source_root {tcl_quote(path)}] \\\n")
        f.write("]\n\n")

        f.write("set syn_memory_files [list \\\n")
        for path in memory_files:
            f.write(f"    [file join $syn_source_root {tcl_quote(path)}] \\\n")
        f.write("]\n\n")

        f.write("set syn_verilog_defines [list \\\n")
        for define in defines:
            f.write(f"    {tcl_quote(define)} \\\n")
        f.write("]\n\n")

        if "memory/itcm.mem" in memory_files:
            f.write(
                "lappend syn_verilog_defines "
                "{ITCM_INIT_FILE=\"itcm.mem\"}\n"
            )
        if "memory/dtcm.mem" in memory_files:
            f.write(
                "lappend syn_verilog_defines "
                "{DTCM_INIT_FILE=\"dtcm.mem\"}\n"
            )
        f.write("\n")

        f.write(
            """
set syn_fs [get_filesets sources_1]
foreach syn_file $syn_source_files {
    if {![file exists $syn_file]} {
        error "Generated source file does not exist: $syn_file"
    }
}
foreach syn_file $syn_memory_files {
    if {![file exists $syn_file]} {
        error "Generated memory initialization file does not exist: $syn_file"
    }
}
if {[llength $syn_source_files] > 0} {
    add_files -norecurse -fileset $syn_fs $syn_source_files
    set_property used_in_synthesis true [get_files -of_objects $syn_fs $syn_source_files]
    set_property used_in_implementation true [get_files -of_objects $syn_fs $syn_source_files]
}
if {[llength $syn_memory_files] > 0} {
    add_files -norecurse -fileset $syn_fs $syn_memory_files
}
set_property include_dirs $syn_include_dirs $syn_fs
set_property verilog_define $syn_verilog_defines $syn_fs
update_compile_order -fileset sources_1
"""
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--bender", default="bender")
    parser.add_argument("--bender-dir", type=Path, default=None)
    parser.add_argument("--wrapper-dir", type=Path, default=None)
    parser.add_argument("--itcm-init-file", type=Path, default=None)
    parser.add_argument("--dtcm-init-file", type=Path, default=None)
    parser.add_argument("--stage-sources-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--target", action="append", default=["verilator", "iverilog", "vcs"])
    parser.add_argument("--define", action="append", default=[])
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    bender_dir = (args.bender_dir or repo_root / "hw/ip/ydrasil_soc").resolve()
    wrapper_dir = (args.wrapper_dir or repo_root / "hw/ip/Xilinx_ip_wrapper/rtl").resolve()
    stage_sources_dir = args.stage_sources_dir.resolve()

    manifest = run_bender_sources(args.bender, bender_dir, args.target)
    files: list[str] = []
    incdirs: list[str] = []
    bender_defines: list[str] = []
    walk_manifest(manifest, files, incdirs, bender_defines)

    wrappers = wrapper_files(wrapper_dir)
    wrapper_modules: set[str] = set()
    for path in wrappers:
        wrapper_modules.update(modules_in_file(path))

    filtered_files: list[str] = []
    skipped: list[str] = []
    for file_name in unique(files):
        path = Path(file_name)
        duplicate_modules = modules_in_file(path) & wrapper_modules
        if duplicate_modules:
            skipped.append(f"{path}:{','.join(sorted(duplicate_modules))}")
            continue
        filtered_files.append(str(path))

    source_paths = [Path(path) for path in unique(
        filtered_files + [str(path.resolve()) for path in wrappers]
    )]
    include_paths = [
        Path(path) for path in unique(incdirs) if Path(path).is_dir()
    ]
    defines = unique(DEFAULT_DEFINES + args.define)

    missing = [str(path) for path in source_paths if not path.is_file()]
    if missing:
        for path in missing:
            print(f"missing source: {path}", file=sys.stderr)
        return 2

    stage_sources_dir.mkdir(parents=True, exist_ok=True)
    staged_source_files: list[str] = []
    for source in source_paths:
        relative = staged_relative_path(source, repo_root)
        copy_file(source, stage_sources_dir / relative)
        staged_source_files.append(relative.as_posix())

    staged_include_dirs: list[str] = []
    for include_dir in include_paths:
        relative = staged_relative_path(include_dir, repo_root)
        stage_include_dir(include_dir, stage_sources_dir / relative)
        staged_include_dirs.append(relative.as_posix())

    memory_files: list[str] = []
    for init_file in (args.itcm_init_file, args.dtcm_init_file):
        if init_file is None:
            continue
        init_path = init_file.resolve()
        if not init_path.is_file():
            print(f"missing memory initialization file: {init_path}", file=sys.stderr)
            return 2
        try:
            memory_files.append(init_path.relative_to(stage_sources_dir).as_posix())
        except ValueError:
            raise SystemExit(
                f"error: memory initialization file is outside staged sources: {init_path}") from None

    for coe_name in ("memory/itcm.coe", "memory/dtcm.coe"):
        if (stage_sources_dir / coe_name).is_file():
            memory_files.append(coe_name)

    metadata = {
        "bender_package": bender_dir.name,
        "targets": args.target,
        "wrapper_modules": sorted(wrapper_modules),
        "itcm_init_file": "memory/itcm.mem" if args.itcm_init_file else None,
        "dtcm_init_file": "memory/dtcm.mem" if args.dtcm_init_file else None,
        "ignored_bender_defines": sorted(unique(bender_defines)),
        "skipped_bender_source_count": len(skipped),
        "source_count": len(staged_source_files),
    }
    write_tcl(
        args.out.resolve(),
        staged_source_files,
        unique(staged_include_dirs),
        defines,
        unique(memory_files),
        metadata,
    )

    print(f"wrote {args.out} with {len(staged_source_files)} staged sources")
    if skipped:
        print("skipped Bender sources shadowed by Xilinx wrappers:")
        for item in skipped:
            print(f"  {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
