#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

#define SOC_YDRASIL
#define ARCH_RISCV
#define ARCH_RISCV32

#define RT_CPUS_NR 1
#define RT_NAME_MAX 16
#define RT_ALIGN_SIZE 16
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000

#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 512

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP

#define RT_USING_DEVICE
#define RT_USING_DEVICE_IPC
#define RT_UNAMED_PIPE_NUMBER 8

#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 256
#define RT_CONSOLE_DEVICE_NAME "console"
#define RT_VER_NUM 0x50201
#define RT_BACKTRACE_LEVEL_MAX_NR 32

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10

#define RT_USING_UTEST
#define UTEST_THR_STACK_SIZE 4096
#define UTEST_THR_PRIORITY 20

#define BSP_USING_SIM_CONSOLE

#ifdef RTT_COREMARK_BUILD
#define BSP_USING_COREMARK
#endif

#endif
