#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

#define SOC_YDRASIL
#define ARCH_RISCV
#define ARCH_RISCV32

#define RT_CPUS_NR 1
#define RT_NAME_MAX 16
#define RT_ALIGN_SIZE 16
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000

#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 512

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP

#define RT_USING_DEVICE
#define RT_USING_DEVICE_IPC
#define RT_UNAMED_PIPE_NUMBER 8

#define RT_KLIBC_USING_VSNPRINTF_STANDARD
#define RT_KLIBC_USING_VSNPRINTF_LONGLONG
#define RT_KLIBC_USING_VSNPRINTF_DECIMAL_SPECIFIERS

#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 256
#define RT_CONSOLE_DEVICE_NAME "uart0"
#ifdef RTT_LEGACY_522_BUILD
#define RT_VER_NUM 0x50202
#else
#define RT_VER_NUM 0x30105
#endif
#define RT_BACKTRACE_LEVEL_MAX_NR 32

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 4096
#define RT_MAIN_THREAD_PRIORITY 10

#define RT_USING_MSH
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_USING_MSH_ONLY
#define FINSH_THREAD_NAME "tshell"
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 8192
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_CMD_SIZE 128
#define MSH_USING_BUILT_IN_COMMANDS
#define FINSH_USING_DESCRIPTION
#define FINSH_ARG_MAX 10

#ifdef RTT_UTEST_BUILD
#define RT_USING_UTEST
#define UTEST_THR_STACK_SIZE 4096
#define UTEST_THR_PRIORITY 20

#define BSP_USING_SIM_CONSOLE
#else
#define BSP_USING_UART0
#define BSP_USING_PLIC
#endif /* RTT_UTEST_BUILD */

#define BSP_USING_MTIME_TICK

#ifdef RTT_COREMARK_BUILD
#define BSP_USING_COREMARK
#endif

#endif
