#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

#define SOC_YDRASIL
#define ARCH_RISCV
#define ARCH_RISCV32

#define RT_CPUS_NR 1
#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_8
#define RT_THREAD_PRIORITY_MAX 8
#define RT_TICK_PER_SECOND 1000

#define IDLE_THREAD_STACK_SIZE 256

#define RT_USING_SEMAPHORE

#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 64
#define RT_CONSOLE_DEVICE_NAME "uart0"
#define RT_VER_NUM 0x40101

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 5

#define RT_USING_MSH
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_THREAD_PRIORITY 6
#define FINSH_THREAD_STACK_SIZE 1024
#define FINSH_USING_SYMTAB
#define FINSH_CMD_SIZE 64
#define FINSH_ARG_MAX 4

#define BSP_USING_UART0
#define BSP_USING_PLIC
#define BSP_USING_MTIME_TICK

#ifdef RTT_COREMARK_BUILD
#define BSP_USING_COREMARK
#endif

#endif
