`ifndef DEFINE_DECODE_SVH
`define DEFINE_DECODE_SVH

`define EX_INFO_BUS_WIDTH 2
`define EX_INFO_BYPASS_BIT 2
`define EX_INFO_ALU EX_INFO_BUS_WIDTH'd0
// `define EX_INFO_MUL EX_INFO_BUS_WIDTH'd1
// `define EX_INFO_DIV EX_INFO_BUS_WIDTH'd2
// `define EX_INFO_CSR EX_INFO_BUS_WIDTH'd3
`define EX_INFO_BJP EX_INFO_BUS_WIDTH'd1
`define EX_INFO_LOAD EX_INFO_BUS_WIDTH'd2
`define EX_INFO_OTHER EX_INFO_BUS_WIDTH'd3



`define ISA_DECODE_GRP_BUS 2:0
`define ISA_DECODE_GRP_WIDTH 3
`define ISA_DECODE_GRP_ALU `ISA_DECODE_GRP_WIDTH'd1
`define ISA_DECODE_GRP_BJP `ISA_DECODE_GRP_WIDTH'd2

`define ISA_DECODE_ALU_BUS_WIDTH (`ISA_DECODE_GRP_WIDTH+14)
`define ISA_DECODE_ALU_LUI (`ISA_DECODE_GRP_WIDTH+0)
`define ISA_DECODE_ALU_AUIPC (`ISA_DECODE_GRP_WIDTH+1)
`define ISA_DECODE_ALU_ADD (`ISA_DECODE_GRP_WIDTH+2)
`define ISA_DECODE_ALU_SUB (`ISA_DECODE_GRP_WIDTH+3)
`define ISA_DECODE_ALU_SLL (`ISA_DECODE_GRP_WIDTH+4)
`define ISA_DECODE_ALU_SLT (`ISA_DECODE_GRP_WIDTH+5)
`define ISA_DECODE_ALU_SLTU (`ISA_DECODE_GRP_WIDTH+6)
`define ISA_DECODE_ALU_XOR (`ISA_DECODE_GRP_WIDTH+7)
`define ISA_DECODE_ALU_SRL (`ISA_DECODE_GRP_WIDTH+8)
`define ISA_DECODE_ALU_SRA (`ISA_DECODE_GRP_WIDTH+9)
`define ISA_DECODE_ALU_OR (`ISA_DECODE_GRP_WIDTH+10)
`define ISA_DECODE_ALU_AND (`ISA_DECODE_GRP_WIDTH+11)
`define ISA_DECODE_ALU_OP2IMM (`ISA_DECODE_GRP_WIDTH+12)
`define ISA_DECODE_ALU_OP1PC (`ISA_DECODE_GRP_WIDTH+13)

`define ISA_DECODE_BJP_BUS_WIDTH (`ISA_DECODE_GRP_WIDTH+8)
`define ISA_DECODE_BJP_JUMP (`ISA_DECODE_GRP_WIDTH+0)
`define ISA_DECODE_BJP_BEQ (`ISA_DECODE_GRP_WIDTH+1)
`define ISA_DECODE_BJP_BNE (`ISA_DECODE_GRP_WIDTH+2)
`define ISA_DECODE_BJP_BLT (`ISA_DECODE_GRP_WIDTH+3)
`define ISA_DECODE_BJP_BGE (`ISA_DECODE_GRP_WIDTH+4)
`define ISA_DECODE_BJP_BLTU (`ISA_DECODE_GRP_WIDTH+5)
`define ISA_DECODE_BJP_BGEU (`ISA_DECODE_GRP_WIDTH+6)
`define ISA_DECODE_BJP_OP1RS1 (`ISA_DECODE_GRP_WIDTH+7)


`endif
