`ifndef DEFINE_ALU_OP_SVH
`define DEFINE_ALU_OP_SVH

//exu_alu的数据通路
`define DATAPATH_MUX_WIDTH (32+32+16)

`define ALU_OP_INFO_WIDTH 5

// ALU操作指令
`define OP_ADD ALU_OP_INFO_WIDTH'h0
`define OP_SUB ALU_OP_INFO_WIDTH'h1
`define OP_SLL ALU_OP_INFO_WIDTH'h2
`define OP_SLT ALU_OP_INFO_WIDTH'h3
`define OP_SLTU ALU_OP_INFO_WIDTH'h4
`define OP_XOR ALU_OP_INFO_WIDTH'h5
`define OP_SRL ALU_OP_INFO_WIDTH'h6
`define OP_SRA ALU_OP_INFO_WIDTH'h7
`define OP_OR ALU_OP_INFO_WIDTH'h8
`define OP_AND ALU_OP_INFO_WIDTH'h9

`define OP_JUMP ALU_OP_INFO_WIDTH'hA

// 分支指令
`define OP_BEQ ALU_OP_INFO_WIDTH'hB
`define OP_BNE ALU_OP_INFO_WIDTH'hC
`define OP_BLT ALU_OP_INFO_WIDTH'hD
`define OP_BGE ALU_OP_INFO_WIDTH'hE
`define OP_BLTU ALU_OP_INFO_WIDTH'hF
`define OP_BGEU ALU_OP_INFO_WIDTH'h10
`define OP_LUI ALU_OP_INFO_WIDTH'h11
`define OP_AUIPC ALU_OP_INFO_WIDTH'h12



`endif
