import os

from building import *


app_root = GetCurrentDir()
sw_root = os.path.abspath(os.path.join(app_root, '..', '..'))
coremark_root = os.path.join(sw_root, 'coremark')
build_root = os.path.abspath(os.getenv('RTT_BUILD_DIR', 'build'))
coremark_variant = os.path.join(build_root, 'app-sources', 'coremark')
app_variant = os.path.join(build_root, 'app-sources', 'rtthread-coremark')

VariantDir(coremark_variant, coremark_root, duplicate=0)
VariantDir(app_variant, app_root, duplicate=0)

algorithm_sources = [
    os.path.join(coremark_variant, name + '.c')
    for name in ('core_list_join', 'core_matrix', 'core_state', 'core_util')
]
core_main_source = os.path.join(coremark_variant, 'core_main.c')

profile = os.getenv('RTT_APP_PROFILE',
                    os.getenv('RTT_COREMARK_PROFILE', 'custom'))
iterations = int(os.getenv('RTT_APP_ITERATIONS',
                           os.getenv('RTT_COREMARK_ITERATIONS', '1')))

defines = [
    ('ITERATIONS', iterations),
    ('PERFORMANCE_RUN', 1),
    ('COREMARK_IGNORE_10S_ERROR', 1),
    ('HAS_FLOAT', 1),
    ('MAIN_HAS_NORETURN', 0),
    ('FLAGS_STR', '\\"RT-Thread-' + profile + '\\"'),
]

common_group = dict(
    depend=[''],
    LOCAL_CPPPATH=[app_root, coremark_root],
    LOCAL_CPPDEFINES=defines,
)

core_cflags = os.getenv('RTT_COREMARK_CORE_CFLAGS', '').strip()
if core_cflags:
    core_cflags = ' ' + core_cflags

algorithm_group = DefineGroup(
    'RT-Thread App: CoreMark algorithms',
    algorithm_sources,
    LOCAL_CFLAGS=core_cflags,
    **common_group
)
entry_group = DefineGroup(
    'RT-Thread App: CoreMark entry',
    [core_main_source],
    LOCAL_CFLAGS=core_cflags,
    depend=[''],
    LOCAL_CPPPATH=[app_root, coremark_root],
    LOCAL_CPPDEFINES=defines + [('main', 'coremark_entry')],
)
port_group = DefineGroup(
    'RT-Thread App: CoreMark port',
    [os.path.join(app_variant, 'main.c'),
     os.path.join(app_variant, 'core_portme.c')],
    **common_group
)

group = [algorithm_group, entry_group, port_group]
Return('group')
